# Basic config
language: php
php:
  - '7.0'
  - '7.1'

# Composer, dependencies and autoloading
install:
  - composer install

# Execute unit tests
script:
  - ./vendor/bin/phpunit --configuration phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 --colors -v src/