# Basic conif
language: php
php:
  - '7.0'

# Composer, dependencies and autoloading
install:
  - composer install

# Execute unit tests
script:
  - phpunit --configuration phpunit.xml
  - ./vendor/bin/humbug
  - ./vendor/bin/phpcs --standard=PSR2 --colors -v src/php/
